In [ ]:
from sklearn.metrics import r2_score ,mean_absolute_error ,mean_squared_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor 
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge , Lasso
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('data/stud.csv')
df

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [3]:
df['total_score']= df['math_score'] + df['reading_score'] + df['writing_score']
df['avg_score'] = df['total_score'] /3

In [4]:
df

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,avg_score
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282,94.000000
996,male,group C,high school,free/reduced,none,62,55,55,172,57.333333
997,female,group C,high school,free/reduced,completed,59,71,65,195,65.000000
998,female,group D,some college,standard,completed,68,78,77,223,74.333333
999,female,group D,some college,free/reduced,none,77,86,86,249,83.000000

In [5]:
X = df.drop('avg_score' , axis=1)
X

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282
996,male,group C,high school,free/reduced,none,62,55,55,172
997,female,group C,high school,free/reduced,completed,59,71,65,195
998,female,group D,some college,standard,completed,68,78,77,223
999,female,group D,some college,free/reduced,none,77,86,86,249

In [6]:
y = df['avg_score']
y

0      72.666667
1      82.333333
2      92.666667
3      49.333333
4      76.333333
         ...
995    94.000000
996    57.333333
997    65.000000
998    74.333333
999    83.000000
Name: avg_score, Length: 1000, dtype: float64

In [7]:
num_features = X.select_dtypes(exclude="object").columns
cat_features = X.select_dtypes(include="object").columns

from sklearn.preprocessing import OneHotEncoder , LabelEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_tranformer = OneHotEncoder()

preprocessor=ColumnTransformer(
    [
        ("OneHotEncoder" , oh_tranformer , cat_features),
        ("StandardScaler" ,numeric_transformer , num_features)
    ]
)

In [8]:
X = preprocessor.fit_transform(X)

In [9]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=42)

In [13]:
def evaluate_model(true , predicted):
    mae = mean_absolute_error(true , predicted)
    mse = mean_squared_error(true , predicted)
    rmse = np.sqrt(mean_squared_error(true , predicted))
    r2 = r2_score(true , predicted)
    return mae , rmse , r2

In [15]:
models ={
    "Linear Regression":LinearRegression(),
    "Ridge":Ridge() ,
    "Lasso":Lasso() ,
    "K_Neighbors_Regressor":KNeighborsRegressor(),
    "Decision_Tree_Regressor":DecisionTreeRegressor(),
    "Random_Forest_Regressor":RandomForestRegressor(),
    "XG_Regresseor":XGBRegressor(),
    "Cat_Boost_Regressor":CatBoostRegressor(),
    "ADA_Boost_Regressor":AdaBoostRegressor(),
}

model_list =[]
r2_list = []

for i in range (len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train , y_train )

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_mae , model_train_rmse ,model_train_r2 = evaluate_model(y_train ,y_train_pred)
    model_test_mae , model_test_rmse ,model_test_r2 = evaluate_model(y_test ,y_test_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model performance for training set')
    print("- root mean squared error: {:.4f}".format(model_train_rmse))
    print("- Mean absolute error :{:.4f}".format(model_train_mae))
    print("- R2 Score : {:.4f}" .format(model_train_r2))

    print("------------------------------------")

    
    print('Model performance for test set')
    print("- root mean squared error: {:.4f}".format(model_test_rmse))
    print("- Mean absolute error :{:.4f}".format(model_test_mae))
    print("- R2 Score : {:.4f}" .format(model_test_r2))
    r2_list.append(model_test_r2)

    print("\n")

Linear Regression
Model performance for training set
- root mean squared error: 0.0000
- Mean absolute error :0.0000
- R2 Score : 1.0000
------------------------------------
Model performance for test set
- root mean squared error: 0.0000
- Mean absolute error :0.0000
- R2 Score : 1.0000


Ridge
Model performance for training set
- root mean squared error: 0.0059
- Mean absolute error :0.0048
- R2 Score : 1.0000
------------------------------------
Model performance for test set
- root mean squared error: 0.0064
- Mean absolute error :0.0049
- R2 Score : 1.0000


Lasso
Model performance for training set
- root mean squared error: 1.0090
- Mean absolute error :0.8075
- R2 Score : 0.9949
------------------------------------
Model performance for test set
- root mean squared error: 1.0557
- Mean absolute error :0.8312
- R2 Score : 0.9948


K_Neighbors_Regressor
Model performance for training set
- root mean squared error: 1.9816
- Mean absolute error :1.5570
- R2 Score : 0.9803
------------------------------------
Model performance for test set
- root mean squared error: 2.6661
- Mean absolute error :1.9230
- R2 Score : 0.9668


Decision_Tree_Regressor
Model performance for training set
- root mean squared error: 0.0000
- Mean absolute error :0.0000
- R2 Score : 1.0000
------------------------------------
Model performance for test set
- root mean squared error: 0.6795
- Mean absolute error :0.0917
- R2 Score : 0.9978


Random_Forest_Regressor
Model performance for training set
- root mean squared error: 0.1048
- Mean absolute error :0.0240
- R2 Score : 0.9999
------------------------------------
Model performance for test set
- root mean squared error: 0.8613
- Mean absolute error :0.1098
- R2 Score : 0.9965


XG_Regresseor
Model performance for training set
- root mean squared error: 0.0122
- Mean absolute error :0.0083
- R2 Score : 1.0000
------------------------------------
Model performance for test set
- root mean squared error: 0.7421
- Mean absolute error :0.1759
- R2 Score : 0.9974


Learning rate set to 0.039525
0:	learn: 13.6799484	total: 162ms	remaining: 2m 42s
1:	learn: 13.2584108	total: 165ms	remaining: 1m 22s
2:	learn: 12.8179526	total: 166ms	remaining: 55.3s
3:	learn: 12.4167497	total: 168ms	remaining: 41.8s
4:	learn: 12.0118991	total: 169ms	remaining: 33.7s
5:	learn: 11.6191358	total: 170ms	remaining: 28.2s
6:	learn: 11.2440436	total: 172ms	remaining: 24.3s
7:	learn: 10.8563510	total: 173ms	remaining: 21.4s
8:	learn: 10.5097595	total: 174ms	remaining: 19.1s
9:	learn: 10.1610477	total: 176ms	remaining: 17.4s
10:	learn: 9.8256432	total: 177ms	remaining: 15.9s
11:	learn: 9.4966609	total: 178ms	remaining: 14.7s
12:	learn: 9.2084559	total: 180ms	remaining: 13.7s
13:	learn: 8.9062914	total: 182ms	remaining: 12.8s
14:	learn: 8.6207817	total: 183ms	remaining: 12s
15:	learn: 8.3330588	total: 184ms	remaining: 11.3s
16:	learn: 8.0878187	total: 185ms	remaining: 10.7s
17:	learn: 7.8496862	total: 187ms	remaining: 10.2s
18:	learn: 7.5932326	total: 188ms	remaining: 9.7s
19:	learn: 7.3588637	total: 189ms	remaining: 9.26s
20:	learn: 7.1234078	total: 190ms	remaining: 8.87s
21:	learn: 6.9079082	total: 192ms	remaining: 8.52s
22:	learn: 6.6928624	total: 193ms	remaining: 8.18s
23:	learn: 6.4833856	total: 194ms	remaining: 7.89s
24:	learn: 6.2897130	total: 195ms	remaining: 7.62s
25:	learn: 6.0973478	total: 196ms	remaining: 7.36s
26:	learn: 5.9156470	total: 199ms	remaining: 7.19s
27:	learn: 5.7288686	total: 202ms	remaining: 7s
28:	learn: 5.5556842	total: 203ms	remaining: 6.79s
29:	learn: 5.3832173	total: 204ms	remaining: 6.61s
30:	learn: 5.2186048	total: 206ms	remaining: 6.43s
31:	learn: 5.0468532	total: 207ms	remaining: 6.27s
32:	learn: 4.8929348	total: 209ms	remaining: 6.12s
33:	learn: 4.7372378	total: 210ms	remaining: 5.96s
34:	learn: 4.5879810	total: 211ms	remaining: 5.83s
35:	learn: 4.4542840	total: 213ms	remaining: 5.69s
36:	learn: 4.3234488	total: 214ms	remaining: 5.57s
37:	learn: 4.1920000	total: 215ms	remaining: 5.45s
38:	learn: 4.0678389	total: 216ms	remaining: 5.33s
39:	learn: 3.9532173	total: 218ms	remaining: 5.22s
40:	learn: 3.8355440	total: 219ms	remaining: 5.12s
41:	learn: 3.7223923	total: 220ms	remaining: 5.03s
42:	learn: 3.6100830	total: 222ms	remaining: 4.94s
43:	learn: 3.4985130	total: 223ms	remaining: 4.85s
44:	learn: 3.3961269	total: 224ms	remaining: 4.76s
45:	learn: 3.2904287	total: 226ms	remaining: 4.68s
46:	learn: 3.1917623	total: 227ms	remaining: 4.61s
47:	learn: 3.0924578	total: 229ms	remaining: 4.54s
48:	learn: 3.0003871	total: 230ms	remaining: 4.47s
49:	learn: 2.9162346	total: 231ms	remaining: 4.4s
50:	learn: 2.8292768	total: 233ms	remaining: 4.33s
51:	learn: 2.7441096	total: 234ms	remaining: 4.27s
52:	learn: 2.6611288	total: 235ms	remaining: 4.2s
53:	learn: 2.5884294	total: 237ms	remaining: 4.14s
54:	learn: 2.5123448	total: 238ms	remaining: 4.08s
55:	learn: 2.4391966	total: 239ms	remaining: 4.03s
56:	learn: 2.3748459	total: 240ms	remaining: 3.98s
57:	learn: 2.3087118	total: 242ms	remaining: 3.92s
58:	learn: 2.2491655	total: 243ms	remaining: 3.87s
59:	learn: 2.1867982	total: 244ms	remaining: 3.82s
60:	learn: 2.1232056	total: 245ms	remaining: 3.77s
61:	learn: 2.0655818	total: 246ms	remaining: 3.73s
62:	learn: 2.0076140	total: 247ms	remaining: 3.68s
63:	learn: 1.9515703	total: 249ms	remaining: 3.63s
64:	learn: 1.8985970	total: 250ms	remaining: 3.59s
65:	learn: 1.8452693	total: 251ms	remaining: 3.55s
66:	learn: 1.7979612	total: 252ms	remaining: 3.51s
67:	learn: 1.7480157	total: 253ms	remaining: 3.47s
68:	learn: 1.6999641	total: 254ms	remaining: 3.43s
69:	learn: 1.6552311	total: 256ms	remaining: 3.4s
70:	learn: 1.6108767	total: 257ms	remaining: 3.36s
71:	learn: 1.5711108	total: 259ms	remaining: 3.33s
72:	learn: 1.5312201	total: 260ms	remaining: 3.3s
73:	learn: 1.4919100	total: 261ms	remaining: 3.26s
74:	learn: 1.4597326	total: 262ms	remaining: 3.23s
75:	learn: 1.4214621	total: 263ms	remaining: 3.2s
76:	learn: 1.3871733	total: 265ms	remaining: 3.17s
77:	learn: 1.3549481	total: 266ms	remaining: 3.15s
78:	learn: 1.3236381	total: 267ms	remaining: 3.12s
79:	learn: 1.2958130	total: 269ms	remaining: 3.09s
80:	learn: 1.2662758	total: 270ms	remaining: 3.06s
81:	learn: 1.2386114	total: 271ms	remaining: 3.03s
82:	learn: 1.2095130	total: 272ms	remaining: 3.01s
83:	learn: 1.1820429	total: 273ms	remaining: 2.98s
84:	learn: 1.1558265	total: 275ms	remaining: 2.96s
85:	learn: 1.1295622	total: 276ms	remaining: 2.93s
86:	learn: 1.1059094	total: 277ms	remaining: 2.91s
87:	learn: 1.0827592	total: 278ms	remaining: 2.88s
88:	learn: 1.0596038	total: 280ms	remaining: 2.86s
89:	learn: 1.0359231	total: 281ms	remaining: 2.84s
90:	learn: 1.0148348	total: 282ms	remaining: 2.82s
91:	learn: 0.9945121	total: 283ms	remaining: 2.79s
92:	learn: 0.9746102	total: 285ms	remaining: 2.78s
93:	learn: 0.9577651	total: 286ms	remaining: 2.75s
94:	learn: 0.9400656	total: 287ms	remaining: 2.73s
95:	learn: 0.9238642	total: 289ms	remaining: 2.72s
96:	learn: 0.9052095	total: 290ms	remaining: 2.7s
97:	learn: 0.8884230	total: 291ms	remaining: 2.68s
98:	learn: 0.8716938	total: 293ms	remaining: 2.66s
99:	learn: 0.8547578	total: 294ms	remaining: 2.65s
100:	learn: 0.8381498	total: 295ms	remaining: 2.63s
101:	learn: 0.8231404	total: 297ms	remaining: 2.61s
102:	learn: 0.8086128	total: 298ms	remaining: 2.59s
103:	learn: 0.7959765	total: 299ms	remaining: 2.58s
104:	learn: 0.7832777	total: 300ms	remaining: 2.56s
105:	learn: 0.7702636	total: 301ms	remaining: 2.54s
106:	learn: 0.7581414	total: 303ms	remaining: 2.53s
107:	learn: 0.7445912	total: 304ms	remaining: 2.51s
108:	learn: 0.7324157	total: 305ms	remaining: 2.49s
109:	learn: 0.7209615	total: 307ms	remaining: 2.48s
110:	learn: 0.7102144	total: 308ms	remaining: 2.47s
111:	learn: 0.6990197	total: 310ms	remaining: 2.45s
112:	learn: 0.6893265	total: 311ms	remaining: 2.44s
113:	learn: 0.6787508	total: 313ms	remaining: 2.43s
114:	learn: 0.6697214	total: 314ms	remaining: 2.42s
115:	learn: 0.6607005	total: 316ms	remaining: 2.4s
116:	learn: 0.6516774	total: 317ms	remaining: 2.39s
117:	learn: 0.6431434	total: 318ms	remaining: 2.38s
118:	learn: 0.6352337	total: 320ms	remaining: 2.37s
119:	learn: 0.6287153	total: 321ms	remaining: 2.35s
120:	learn: 0.6215771	total: 322ms	remaining: 2.34s
121:	learn: 0.6137612	total: 323ms	remaining: 2.33s
122:	learn: 0.6075301	total: 325ms	remaining: 2.32s
123:	learn: 0.6016559	total: 326ms	remaining: 2.31s
124:	learn: 0.5943358	total: 328ms	remaining: 2.29s
125:	learn: 0.5881015	total: 330ms	remaining: 2.29s
126:	learn: 0.5835796	total: 331ms	remaining: 2.27s
127:	learn: 0.5814287	total: 332ms	remaining: 2.26s
128:	learn: 0.5753176	total: 333ms	remaining: 2.25s
129:	learn: 0.5699449	total: 335ms	remaining: 2.24s
130:	learn: 0.5644641	total: 336ms	remaining: 2.23s
131:	learn: 0.5617933	total: 338ms	remaining: 2.22s
132:	learn: 0.5565400	total: 339ms	remaining: 2.21s
133:	learn: 0.5515320	total: 340ms	remaining: 2.2s
134:	learn: 0.5488640	total: 342ms	remaining: 2.19s
135:	learn: 0.5439422	total: 344ms	remaining: 2.18s
136:	learn: 0.5385603	total: 346ms	remaining: 2.18s
137:	learn: 0.5342708	total: 347ms	remaining: 2.17s
138:	learn: 0.5291477	total: 348ms	remaining: 2.16s
139:	learn: 0.5259258	total: 350ms	remaining: 2.15s
140:	learn: 0.5220964	total: 351ms	remaining: 2.14s
141:	learn: 0.5205182	total: 352ms	remaining: 2.12s
142:	learn: 0.5168608	total: 353ms	remaining: 2.12s
143:	learn: 0.5112255	total: 355ms	remaining: 2.11s
144:	learn: 0.5097699	total: 356ms	remaining: 2.1s
145:	learn: 0.5059266	total: 357ms	remaining: 2.09s
146:	learn: 0.5019366	total: 359ms	remaining: 2.08s
147:	learn: 0.4983606	total: 360ms	remaining: 2.07s
148:	learn: 0.4943261	total: 361ms	remaining: 2.06s
149:	learn: 0.4905898	total: 363ms	remaining: 2.06s
150:	learn: 0.4873366	total: 365ms	remaining: 2.05s
151:	learn: 0.4839088	total: 366ms	remaining: 2.04s
152:	learn: 0.4801092	total: 368ms	remaining: 2.04s
153:	learn: 0.4789358	total: 369ms	remaining: 2.03s
154:	learn: 0.4752088	total: 371ms	remaining: 2.02s
155:	learn: 0.4740926	total: 371ms	remaining: 2.01s
156:	learn: 0.4708904	total: 373ms	remaining: 2s
157:	learn: 0.4696910	total: 374ms	remaining: 1.99s
158:	learn: 0.4657709	total: 375ms	remaining: 1.99s
159:	learn: 0.4646423	total: 377ms	remaining: 1.98s
160:	learn: 0.4623534	total: 379ms	remaining: 1.97s
161:	learn: 0.4608422	total: 380ms	remaining: 1.97s
162:	learn: 0.4583947	total: 382ms	remaining: 1.96s
163:	learn: 0.4573758	total: 383ms	remaining: 1.95s
164:	learn: 0.4557417	total: 385ms	remaining: 1.95s
165:	learn: 0.4547611	total: 386ms	remaining: 1.94s
166:	learn: 0.4523424	total: 388ms	remaining: 1.93s
167:	learn: 0.4496123	total: 389ms	remaining: 1.93s
168:	learn: 0.4486699	total: 390ms	remaining: 1.92s
169:	learn: 0.4469046	total: 392ms	remaining: 1.91s
170:	learn: 0.4455408	total: 393ms	remaining: 1.91s
171:	learn: 0.4425314	total: 395ms	remaining: 1.9s
172:	learn: 0.4407020	total: 397ms	remaining: 1.9s
173:	learn: 0.4396721	total: 398ms	remaining: 1.89s
174:	learn: 0.4386338	total: 399ms	remaining: 1.88s
175:	learn: 0.4374872	total: 401ms	remaining: 1.88s
176:	learn: 0.4358857	total: 403ms	remaining: 1.87s
177:	learn: 0.4349929	total: 404ms	remaining: 1.86s
178:	learn: 0.4340267	total: 404ms	remaining: 1.85s
179:	learn: 0.4331871	total: 406ms	remaining: 1.85s
180:	learn: 0.4323377	total: 407ms	remaining: 1.84s
181:	learn: 0.4315354	total: 408ms	remaining: 1.83s
182:	learn: 0.4306415	total: 409ms	remaining: 1.82s
183:	learn: 0.4299667	total: 410ms	remaining: 1.82s
184:	learn: 0.4277227	total: 411ms	remaining: 1.81s
185:	learn: 0.4255889	total: 412ms	remaining: 1.8s
186:	learn: 0.4249862	total: 413ms	remaining: 1.8s
187:	learn: 0.4242971	total: 414ms	remaining: 1.79s
188:	learn: 0.4236319	total: 415ms	remaining: 1.78s
189:	learn: 0.4215734	total: 416ms	remaining: 1.77s
190:	learn: 0.4204875	total: 417ms	remaining: 1.77s
191:	learn: 0.4197065	total: 419ms	remaining: 1.76s
192:	learn: 0.4190494	total: 421ms	remaining: 1.76s
193:	learn: 0.4164742	total: 422ms	remaining: 1.75s
194:	learn: 0.4138789	total: 423ms	remaining: 1.75s
195:	learn: 0.4118401	total: 425ms	remaining: 1.74s
196:	learn: 0.4108971	total: 426ms	remaining: 1.74s
197:	learn: 0.4100791	total: 427ms	remaining: 1.73s
198:	learn: 0.4092277	total: 429ms	remaining: 1.73s
199:	learn: 0.4086301	total: 430ms	remaining: 1.72s
200:	learn: 0.4081237	total: 431ms	remaining: 1.71s
201:	learn: 0.4076724	total: 432ms	remaining: 1.71s
202:	learn: 0.4070996	total: 433ms	remaining: 1.7s
203:	learn: 0.4064859	total: 434ms	remaining: 1.69s
204:	learn: 0.4058866	total: 434ms	remaining: 1.68s
205:	learn: 0.4028426	total: 436ms	remaining: 1.68s
206:	learn: 0.4024261	total: 437ms	remaining: 1.67s
207:	learn: 0.4019511	total: 437ms	remaining: 1.67s
208:	learn: 0.4012799	total: 439ms	remaining: 1.66s
209:	learn: 0.4003972	total: 441ms	remaining: 1.66s
210:	learn: 0.3999458	total: 442ms	remaining: 1.65s
211:	learn: 0.3994978	total: 443ms	remaining: 1.64s
212:	learn: 0.3991024	total: 443ms	remaining: 1.64s
213:	learn: 0.3983779	total: 445ms	remaining: 1.63s
214:	learn: 0.3979615	total: 446ms	remaining: 1.63s
215:	learn: 0.3974736	total: 446ms	remaining: 1.62s
216:	learn: 0.3970709	total: 447ms	remaining: 1.61s
217:	learn: 0.3963296	total: 448ms	remaining: 1.61s
218:	learn: 0.3947943	total: 449ms	remaining: 1.6s
219:	learn: 0.3944138	total: 450ms	remaining: 1.6s
220:	learn: 0.3940404	total: 451ms	remaining: 1.59s
221:	learn: 0.3936740	total: 452ms	remaining: 1.58s
222:	learn: 0.3932491	total: 453ms	remaining: 1.58s
223:	learn: 0.3928342	total: 453ms	remaining: 1.57s
224:	learn: 0.3924906	total: 454ms	remaining: 1.56s
225:	learn: 0.3920931	total: 455ms	remaining: 1.56s
226:	learn: 0.3910063	total: 457ms	remaining: 1.55s
227:	learn: 0.3887302	total: 458ms	remaining: 1.55s
228:	learn: 0.3883534	total: 459ms	remaining: 1.54s
229:	learn: 0.3880406	total: 459ms	remaining: 1.54s
230:	learn: 0.3876796	total: 460ms	remaining: 1.53s
231:	learn: 0.3873271	total: 461ms	remaining: 1.52s
232:	learn: 0.3854221	total: 462ms	remaining: 1.52s
233:	learn: 0.3841153	total: 464ms	remaining: 1.52s
234:	learn: 0.3819882	total: 465ms	remaining: 1.51s
235:	learn: 0.3794302	total: 467ms	remaining: 1.51s
236:	learn: 0.3787300	total: 468ms	remaining: 1.51s
237:	learn: 0.3784134	total: 469ms	remaining: 1.5s
238:	learn: 0.3781042	total: 470ms	remaining: 1.5s
239:	learn: 0.3764836	total: 472ms	remaining: 1.49s
240:	learn: 0.3751098	total: 473ms	remaining: 1.49s
241:	learn: 0.3726955	total: 475ms	remaining: 1.49s
242:	learn: 0.3724044	total: 476ms	remaining: 1.48s
243:	learn: 0.3719333	total: 477ms	remaining: 1.48s
244:	learn: 0.3716556	total: 477ms	remaining: 1.47s
245:	learn: 0.3712045	total: 478ms	remaining: 1.47s
246:	learn: 0.3689239	total: 480ms	remaining: 1.46s
247:	learn: 0.3675291	total: 482ms	remaining: 1.46s
248:	learn: 0.3672709	total: 482ms	remaining: 1.46s
249:	learn: 0.3657317	total: 484ms	remaining: 1.45s
250:	learn: 0.3654833	total: 485ms	remaining: 1.45s
251:	learn: 0.3652407	total: 485ms	remaining: 1.44s
252:	learn: 0.3650038	total: 486ms	remaining: 1.43s
253:	learn: 0.3636347	total: 487ms	remaining: 1.43s
254:	learn: 0.3622427	total: 489ms	remaining: 1.43s
255:	learn: 0.3620190	total: 489ms	remaining: 1.42s
256:	learn: 0.3603677	total: 491ms	remaining: 1.42s
257:	learn: 0.3592285	total: 493ms	remaining: 1.42s
258:	learn: 0.3587245	total: 494ms	remaining: 1.41s
259:	learn: 0.3571687	total: 496ms	remaining: 1.41s
260:	learn: 0.3564534	total: 498ms	remaining: 1.41s
261:	learn: 0.3557568	total: 499ms	remaining: 1.41s
262:	learn: 0.3550986	total: 501ms	remaining: 1.4s
263:	learn: 0.3544658	total: 502ms	remaining: 1.4s
264:	learn: 0.3532882	total: 504ms	remaining: 1.4s
265:	learn: 0.3528594	total: 506ms	remaining: 1.4s
266:	learn: 0.3524623	total: 507ms	remaining: 1.39s
267:	learn: 0.3520782	total: 509ms	remaining: 1.39s
268:	learn: 0.3517066	total: 510ms	remaining: 1.39s
269:	learn: 0.3506291	total: 512ms	remaining: 1.38s
270:	learn: 0.3500867	total: 513ms	remaining: 1.38s
271:	learn: 0.3498608	total: 515ms	remaining: 1.38s
272:	learn: 0.3493427	total: 516ms	remaining: 1.37s
273:	learn: 0.3480042	total: 518ms	remaining: 1.37s
274:	learn: 0.3476830	total: 519ms	remaining: 1.37s
275:	learn: 0.3471928	total: 521ms	remaining: 1.37s
276:	learn: 0.3464763	total: 522ms	remaining: 1.36s
277:	learn: 0.3462696	total: 524ms	remaining: 1.36s
278:	learn: 0.3458132	total: 525ms	remaining: 1.36s
279:	learn: 0.3453998	total: 527ms	remaining: 1.35s
280:	learn: 0.3442052	total: 528ms	remaining: 1.35s
281:	learn: 0.3440243	total: 530ms	remaining: 1.35s
282:	learn: 0.3438478	total: 531ms	remaining: 1.34s
283:	learn: 0.3435282	total: 532ms	remaining: 1.34s
284:	learn: 0.3433527	total: 533ms	remaining: 1.34s
285:	learn: 0.3429872	total: 535ms	remaining: 1.33s
286:	learn: 0.3426388	total: 537ms	remaining: 1.33s
287:	learn: 0.3424838	total: 538ms	remaining: 1.33s
288:	learn: 0.3416485	total: 539ms	remaining: 1.33s
289:	learn: 0.3408830	total: 541ms	remaining: 1.32s
290:	learn: 0.3396448	total: 543ms	remaining: 1.32s
291:	learn: 0.3393525	total: 544ms	remaining: 1.32s
292:	learn: 0.3391453	total: 545ms	remaining: 1.32s
293:	learn: 0.3388346	total: 547ms	remaining: 1.31s
294:	learn: 0.3386972	total: 548ms	remaining: 1.31s
295:	learn: 0.3385630	total: 550ms	remaining: 1.31s
296:	learn: 0.3384321	total: 551ms	remaining: 1.3s
297:	learn: 0.3376899	total: 553ms	remaining: 1.3s
298:	learn: 0.3369408	total: 555ms	remaining: 1.3s
299:	learn: 0.3356846	total: 557ms	remaining: 1.3s
300:	learn: 0.3355607	total: 558ms	remaining: 1.29s
301:	learn: 0.3354397	total: 560ms	remaining: 1.29s
302:	learn: 0.3353216	total: 561ms	remaining: 1.29s
303:	learn: 0.3352063	total: 562ms	remaining: 1.29s
304:	learn: 0.3350437	total: 564ms	remaining: 1.28s
305:	learn: 0.3349191	total: 566ms	remaining: 1.28s
306:	learn: 0.3336585	total: 567ms	remaining: 1.28s
307:	learn: 0.3330256	total: 569ms	remaining: 1.28s
308:	learn: 0.3328729	total: 571ms	remaining: 1.28s
309:	learn: 0.3318695	total: 573ms	remaining: 1.27s
310:	learn: 0.3313089	total: 574ms	remaining: 1.27s
311:	learn: 0.3300254	total: 576ms	remaining: 1.27s
312:	learn: 0.3293132	total: 578ms	remaining: 1.27s
313:	learn: 0.3292127	total: 579ms	remaining: 1.26s
314:	learn: 0.3281455	total: 581ms	remaining: 1.26s
315:	learn: 0.3280480	total: 582ms	remaining: 1.26s
316:	learn: 0.3275208	total: 584ms	remaining: 1.26s
317:	learn: 0.3274267	total: 585ms	remaining: 1.25s
318:	learn: 0.3273349	total: 586ms	remaining: 1.25s
319:	learn: 0.3266015	total: 587ms	remaining: 1.25s
320:	learn: 0.3254300	total: 589ms	remaining: 1.25s
321:	learn: 0.3244078	total: 591ms	remaining: 1.24s
322:	learn: 0.3232780	total: 592ms	remaining: 1.24s
323:	learn: 0.3226228	total: 594ms	remaining: 1.24s
324:	learn: 0.3219314	total: 596ms	remaining: 1.24s
325:	learn: 0.3206056	total: 597ms	remaining: 1.23s
326:	learn: 0.3200240	total: 599ms	remaining: 1.23s
327:	learn: 0.3191114	total: 600ms	remaining: 1.23s
328:	learn: 0.3190267	total: 602ms	remaining: 1.23s
329:	learn: 0.3182012	total: 603ms	remaining: 1.23s
330:	learn: 0.3168818	total: 605ms	remaining: 1.22s
331:	learn: 0.3163466	total: 606ms	remaining: 1.22s
332:	learn: 0.3153474	total: 608ms	remaining: 1.22s
333:	learn: 0.3144133	total: 610ms	remaining: 1.22s
334:	learn: 0.3143334	total: 611ms	remaining: 1.21s
335:	learn: 0.3133128	total: 612ms	remaining: 1.21s
336:	learn: 0.3126849	total: 614ms	remaining: 1.21s
337:	learn: 0.3117925	total: 616ms	remaining: 1.21s
338:	learn: 0.3112837	total: 617ms	remaining: 1.2s
339:	learn: 0.3111611	total: 619ms	remaining: 1.2s
340:	learn: 0.3104018	total: 621ms	remaining: 1.2s
341:	learn: 0.3099337	total: 623ms	remaining: 1.2s
342:	learn: 0.3087987	total: 624ms	remaining: 1.2s
343:	learn: 0.3079797	total: 626ms	remaining: 1.19s
344:	learn: 0.3078089	total: 628ms	remaining: 1.19s
345:	learn: 0.3074041	total: 629ms	remaining: 1.19s
346:	learn: 0.3065139	total: 631ms	remaining: 1.19s

In [16]:
pd.DataFrame(list(zip(model_list ,r2_list)) ,columns=['Model Name' ,'R2_score']).sort_values(by=["R2_score"] , ascending=False)

                Model Name  R2_score
0        Linear Regression  1.000000
1                    Ridge  1.000000
4  Decision_Tree_Regressor  0.997846
6            XG_Regresseor  0.997431
5  Random_Forest_Regressor  0.996539
7      Cat_Boost_Regressor  0.994961
2                    Lasso  0.994801
8      ADA_Boost_Regressor  0.990064
3    K_Neighbors_Regressor  0.966842

In [17]:
lin_model = LinearRegression(fit_intercept=True )
lin_model = lin_model.fit(X_train , y_train )
y_pred = lin_model.predict(X_test)
score = r2_score(y_test , y_pred) *100

In [18]:
pred_df = pd.DataFrame(
    {
        'Actual value':y_test,
        'Predicted value':y_pred,
        'Difference':y_test-y_pred ,

    }
)

pred_df

     Actual value  Predicted value    Difference
521     87.000000        87.000000  0.000000e+00
737     64.000000        64.000000  7.105427e-15
740     75.000000        75.000000  1.421085e-14
660     74.666667        74.666667  2.842171e-14
411     81.666667        81.666667  2.842171e-14
..            ...              ...           ...
408     55.000000        55.000000  0.000000e+00
332     57.000000        57.000000  1.421085e-14
208     77.000000        77.000000  0.000000e+00
613     72.000000        72.000000  1.421085e-14
78      69.000000        69.000000  1.421085e-14

[200 rows x 3 columns]